# Generated by Django 2.1.3 on 2018-11-07 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='goalie',
            new_name='goalie_user',
        ),
        migrations.AddField(
            model_name='message',
            name='game_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gameRenter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
