# Generated by Django 2.1.3 on 2018-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0002_auto_20181107_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default='1970-01-01T00:00:00Z'),
        ),
    ]
