# Generated by Django 2.1.3 on 2018-11-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0003_auto_20181107_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit_card_number',
            field=models.IntegerField(default=0),
        ),
    ]
