# Generated by Django 2.1.3 on 2018-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancellations',
            field=models.IntegerField(default=0),
        ),
    ]
