# Generated by Django 2.1.3 on 2019-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0006_profile_cancellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(default='No location string given', max_length=512),
        ),
    ]
